name: Test Reusable Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-reusable-workflow:
    uses: ./.github/workflows/reusable-main.yml
    with:
      folder: "my-test-folder"
  
