name: Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      folder:
        required: true 
        type: string


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        run: echo "Hello"
