name: Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to use for the workflow'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Folder
        run: echo "Working in ${{ inputs.folder }}"

  terraform_2:
    runs-on: ubuntu-latest
    steps:
    
      - name: Print Folderx
        run: echo "Working in 2_${{ inputs.folder }}"