name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-workflow:
    uses: Anatolich911/task/.github/workflows/reusable_main.yml@master
    with:
      folder: here
  
