name: Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to use for the workflow'
        required: false
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        run: echo "Working in folder"
