name: Test Reusable Terraform Plan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-reusable-workflow:
    uses: ./.github/workflows/reusable-terraform-plan.yml@master
    with:
      folder: "my-test-folder"

  
